### ISSUE TITLE
Running configure throws sh command not found error

### ISSUE THREAD

**Issue by Jaker0** [afcowie/java-gnome#16]
I'm running Parabola Linux and when I try to do ./configure from the root directory, it seems to run normally until this is outputted: 

'''Check for required system libraries:
 - Cairo                           sh: pkg-config: command not found
sh: pkg-config: command not found
not found!

In order to build java-gnome, you will need the GNOME
development libraries. Depending on what you have installed,
this could be a considerable set of packages, but if you
want to be a GNOME hacker, that's the way it is.

On a Arch system, you should be able to satisfy this
requirement by doing:

     # pacman -S cairo

Failed to complete configuration.'''

**Comment by afcowie** [comment]
I think that's saying you need `pkg-config` installed, which is (on a Fedora system) provided by the **pkg-config** package. Perhaps something similar will work in your case. Good luck!

**Comment by Jaker0** [comment]
Ugh, stupid me. I installed it with `pacman -S pkg-config` since I'm running Parabola, which is a derivative of Arch. Thanks for the reply, anyway.
